/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/meshes/GameBoard.glb -o src/meshes/GameBoard.tsx -r public -t -k -s -p 7 
Modified by: Aeroplane GLTFJSX Generator v1.9.3
*/

import { Group, Mesh, MeshStandardMaterial } from "three";
import { forwardRef, ForwardedRef, useEffect, useImperativeHandle, ForwardRefExoticComponent, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import useM_Board from "@materials/M_Board";
import { GLTFJSXUtils } from "@utils/GLTFJSXUtils";
import { GLTF } from "three-stdlib";
import { ObjectUtils } from "@utils/ObjectUtils";
import { assetPath } from "@utils/Config";

const mesh = assetPath("/meshes/GameBoard.glb");

type GLTFResult = GLTF & {
    nodes: {
        GameBoard: Mesh;
    }
    materials: {
        M_Board: MeshStandardMaterial;
    }
}

export type Handle = {
    root: Group | null;
    meshes: GLTFResult["nodes"];
    materials: GLTFResult["materials"];
};
export function useHandle(ref: ForwardedRef<Group>) {
    const handle = useRef<Handle>(null);
    useEffect(() => {
        if (!ref) return;
        if (typeof ref === "function") ref(handle.current?.root ?? null);
        else ref.current = handle.current?.root ?? null;
    }, [handle, ref]);
    return handle;
};
export default forwardRef<Handle, JSX.IntrinsicElements["group"]>(function Model(props, ref) {
    const group = useRef<Group>(null);
    const { nodes, materials } = useGLTF(mesh) as GLTFResult;
    materials.M_Board = useM_Board();
    useImperativeHandle(ref, () => GLTFJSXUtils.createHandle<Handle>({ root: group.current }, nodes, materials), [group, nodes, materials]);
    return (
        <group ref={group} {...props} dispose={null}>
            <mesh name="GameBoard" receiveShadow={props.receiveShadow} castShadow={props.castShadow} {...ObjectUtils.pick(nodes.GameBoard, "geometry", "morphTargetDictionary", "morphTargetInfluences")} material={materials.M_Board} raycast={props.raycast} renderOrder={props.renderOrder} layers={props.layers} />
        </group>
    );
});

useGLTF.preload(mesh, true, true);
